checks:
  php: true
filter:
  excluded_paths:
  - vendor/*
  - doc/*
  - tests/*
  - examples/*
coding_style:
  php:
    spaces:
      around_operators:
        unary_additive: true
        concatenation: true
tools:
  php_code_sniffer: true
  php_cs_fixer:
    config:
      level: psr2