checks:
    php: true
filter:
    excluded_paths:
        [vendor/*, doc/*, tests/*, examples/*]
coding_style:
    php:
        spaces:
            around_operators:
                unary_additive: true
                concatenation: true
tools:
    php_code_sniffer: true
    php_cs_fixer:
        config: { level: psr2 } # or psr1 if you would just like to get fixes for PSR1
build:
    tests:
        override:
            -
                command: 'phpunit --coverage-clover=clover'
                coverage:
                    file: 'clover'
                    format: 'clover'