checks:
    php: true
filter:
    excluded_paths:
        - tests/*
coding_style:
    php:
        spaces:
            around_operators:
                unary_additive: true
                concatenation: true