language: php
sudo: true

matrix:
  fast_finish: true
  include:
  - php: 7.0
    env: deps=low
  - php: 7.0
    env: WITH_CRYPTO=true
  - php: 7.1
    env: deps=low
  - php: 7.1
    env: WITH_CRYPTO=true
    env:
        - COMPOSER_FLAGS="--prefer-lowest --prefer-stable"
        - COVERAGE=true
        - PHPUNIT_FLAGS="--coverage-clover=coverage.clover"
        
before_install:
- composer install --dev

install:
  - travis_retry composer update ${COMPOSER_FLAGS} --prefer-source --no-interaction
  
script:
  - vendor/bin/phpunit ${PHPUNIT_FLAGS}
  
after_script:
  - if [[ "$COVERAGE" = true ]]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [[ "$COVERAGE" = true ]]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi