language: php
sudo: true
php:
- '7.0'
- hhvm
- nightly
matrix:
  fast_finish: true
  include:
  - php: 7.0
    env: deps=low
  - php: 7.0
    env: WITH_CRYPTO=true
  - php: 7.1
    env: deps=low
  - php: 7.1
    env: WITH_CRYPTO=true
  - php: hhvm
    env: deps=low
  - php: nightly
    env: deps=low
  - php: nightly
    env: WITH_CRYPTO=true
before_install:
- composer install --dev