language: php
sudo: true

matrix:
  fast_finish: true
  include:
  - php: 7.0
    env: deps=low
  - php: 7.0
    env: WITH_CRYPTO=true
  - php: 7.1
    env: deps=low
  - php: 7.1
    env: WITH_CRYPTO=true
    env:
        - COMPOSER_FLAGS="--prefer-lowest --prefer-stable"
        - COVERAGE=true
        - PHPUNIT_FLAGS="--coverage-clover=coverage.clover"
        - CODECOV_TOKEN="a428b30b-32ca-4f26-a2cf-3447647f58d2"
        
before_install:
- composer install --dev
- travis_retry composer self-update

script:
  - vendor/bin/phpunit ${PHPUNIT_FLAGS}
  
after_script:
  - if [[ "$COVERAGE" = true ]]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [[ "$COVERAGE" = true ]]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi
  
after_success:
  - bash <(curl -s https://codecov.io/bash)