language: php
sudo: true
php:
- '5.6'
- '7.0'
- hhvm
- nightly
matrix:
  fast_finish: true
  include:
  - php: 5.6
    env: deps=low
  - php: 5.6
    env: WITH_CRYPTO=true
  - php: 7.0
    env: deps=low
  - php: 7.0
    env: WITH_CRYPTO=true
  - php: 7.1
  - php: hhvm
  - php: hhvm
    env: deps=low
  - php: nightly
before_install:
- composer install --dev