sudo: true

language: php

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.local
    - vendor

matrix:
  fast_finish: true
  include:
    - php: 7
      env:
        - DEPS=latest
    - php: 7.1
      env:
        - DEPS=lowest
    - php: 7.1
      env:
        - DEPS=locked
    - php: 7.1
      env:
        - DEPS=latest
    - php: hhvm
      env:
        - DEPS=lowest
    - php: hhvm
      env:
        - DEPS=locked
    - php: hhvm
      env:
        - DEPS=latest
      env:
        - COMPOSER_FLAGS="--prefer-lowest --prefer-stable"
        - COVERAGE=true
        - PHPUNIT_FLAGS="--coverage-clover=coverage.clover"
        - CODECOV_TOKEN="a428b30b-32ca-4f26-a2cf-3447647f58d2"

  allow_failures:
    - php: hhvm

before_install:
  - if [[ $TEST_COVERAGE != 'true' ]]; then phpenv config-rm xdebug.ini || return 0 ; fi
  - composer install --dev
  - travis_retry composer self-update

install:
  - travis_retry composer install $COMPOSER_ARGS --ignore-platform-reqs
  - if [[ $TRAVIS_PHP_VERSION =~ ^5.6 ]]; then travis_retry composer update $COMPOSER_ARGS --with-dependencies $LEGACY_DEPS ; fi
  - if [[ $DEPS == 'latest' ]]; then travis_retry composer update $COMPOSER_ARGS ; fi
  - if [[ $DEPS == 'lowest' ]]; then travis_retry composer update --prefer-lowest --prefer-stable $COMPOSER_ARGS ; fi
  - if [[ $TEST_COVERAGE == 'true' ]]; then travis_retry composer require --dev $COMPOSER_ARGS $COVERAGE_DEPS ; fi
  - composer show
script:
  - vendor/bin/phpunit ${PHPUNIT_FLAGS}
  - if [[ $CS_CHECK == 'true' ]]; then composer cs-check ; fi
  - if [[ $CS_CHECK == 'true' ]]; then composer license-check ; fi


after_script:
  - if [[ "$COVERAGE" = true ]]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [[ "$COVERAGE" = true ]]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi

after_success:
  - bash <(curl -s https://codecov.io/bash)